import { SidebarNavItem } from "@/types/nav-item";

interface DocsConfig {
  sidebarNav: SidebarNavItem[];
}

export const docsConfig: DocsConfig = {
  sidebarNav: [
    {
      title: "Getting Started",
      items: [
        {
          title: "Introduction",
          href: "/docs",
          items: [],
        },
      ],
    },
    {
      title: "Components",
      items: [
        {
          disabled: true,
          files: ["ui/accordion.tsx"],
          title: "Accordion",
          href: "/docs/components/accordion",
          items: [],
        },
        {
          disabled: true,
          files: ["ui/alert.tsx"],
          title: "Alert",
          href: "/docs/components/alert",
          items: [],
        },
        {
          disabled: true,
          files: ["ui/alert-dialog.tsx"],
          title: "Alert Dialog",
          href: "/docs/components/alert-dialog",
          items: [],
        },
        {
          disabled: true,
          files: ["ui/aspect-ratio.tsx"],
          title: "Aspect Ratio",
          href: "/docs/components/aspect-ratio",
          items: [],
        },
        {
          disabled: true,
          files: ["ui/avatar.tsx"],
          title: "Avatar",
          href: "/docs/components/avatar",
          items: [],
        },
        {
          disabled: true,
          files: ["ui/badge.tsx"],
          title: "Badge",
          href: "/docs/components/badge",
          items: [],
        },
        {
          disabled: true,
          files: ["ui/button.tsx"],
          title: "Button",
          href: "/docs/components/button",
          items: [],
        },
        {
          disabled: true,
          files: ["ui/calendar.tsx"],
          title: "Calendar",
          href: "/docs/components/calendar",
          items: [],
        },
        {
          disabled: true,
          files: ["ui/card.tsx"],
          title: "Card",
          href: "/docs/components/card",
          items: [],
        },
        {
          disabled: true,
          files: ["ui/carousel.tsx"],
          title: "Carousel",
          href: "/docs/components/carousel",
          items: [],
          label: "New",
        },
        {
          disabled: true,
          files: ["ui/checkbox.tsx"],
          title: "Checkbox",
          href: "/docs/components/checkbox",
          items: [],
        },
        {
          disabled: true,
          files: ["ui/collapsible.tsx"],
          title: "Collapsible",
          href: "/docs/components/collapsible",
          items: [],
        },
        {
          disabled: true,
          title: "Combobox",
          href: "/docs/components/combobox",
          items: [],
        },
        {
          disabled: true,
          files: ["ui/command.tsx"],
          title: "Command",
          href: "/docs/components/command",
          items: [],
        },
        {
          disabled: true,
          files: ["ui/context-menu.tsx"],
          title: "Context Menu",
          href: "/docs/components/context-menu",
          items: [],
        },
        {
          disabled: true,
          title: "Data Table",
          href: "/docs/components/data-table",
          items: [],
        },
        {
          disabled: true,
          title: "Date Picker",
          href: "/docs/components/date-picker",
          items: [],
        },
        {
          disabled: true,
          files: ["ui/dialog.tsx"],
          title: "Dialog",
          href: "/docs/components/dialog",
          items: [],
        },
        {
          disabled: true,
          files: ["ui/drawer.tsx"],
          title: "Drawer",
          href: "/docs/components/drawer",
          items: [],
          label: "New",
        },
        {
          disabled: true,
          files: ["ui/dropdown-menu.tsx"],
          title: "Dropdown Menu",
          href: "/docs/components/dropdown-menu",
          items: [],
        },
        {
          disabled: true,
          files: ["ui/form.tsx"],
          title: "Form",
          href: "/docs/components/form",
          items: [],
        },
        {
          disabled: true,
          files: ["ui/hover-card.tsx"],
          title: "Hover Card",
          href: "/docs/components/hover-card",
          items: [],
        },
        {
          disabled: true,
          files: ["ui/input.tsx"],
          title: "Input",
          href: "/docs/components/input",
          items: [],
        },
        {
          disabled: true,
          files: ["ui/label.tsx"],
          title: "Label",
          href: "/docs/components/label",
          items: [],
        },
        {
          disabled: true,
          files: ["ui/menubar.tsx"],
          title: "Menubar",
          href: "/docs/components/menubar",
          items: [],
        },
        {
          disabled: true,
          files: ["ui/navigation-menu.tsx"],
          title: "Navigation Menu",
          href: "/docs/components/navigation-menu",
          items: [],
        },
        {
          disabled: true,
          files: ["ui/pagination.tsx"],
          title: "Pagination",
          href: "/docs/components/pagination",
          items: [],
          label: "New",
        },
        {
          disabled: true,
          files: ["ui/popover.tsx"],
          title: "Popover",
          href: "/docs/components/popover",
          items: [],
        },
        {
          disabled: true,
          files: ["ui/progress.tsx"],
          title: "Progress",
          href: "/docs/components/progress",
          items: [],
        },
        {
          disabled: true,
          files: ["ui/radio-group.tsx"],
          title: "Radio Group",
          href: "/docs/components/radio-group",
          items: [],
        },
        {
          disabled: true,
          files: ["ui/resizable.tsx"],
          title: "Resizable",
          href: "/docs/components/resizable",
          items: [],
          label: "New",
        },
        {
          disabled: true,
          files: ["ui/scroll-area.tsx"],
          title: "Scroll Area",
          href: "/docs/components/scroll-area",
          items: [],
        },
        {
          disabled: true,
          files: ["ui/select.tsx"],
          title: "Select",
          href: "/docs/components/select",
          items: [],
        },
        {
          disabled: true,
          files: ["ui/separator.tsx"],
          title: "Separator",
          href: "/docs/components/separator",
          items: [],
        },
        {
          disabled: true,
          files: ["ui/sheet.tsx"],
          title: "Sheet",
          href: "/docs/components/sheet",
          items: [],
        },
        {
          disabled: true,
          files: ["ui/skeleton.tsx"],
          title: "Skeleton",
          href: "/docs/components/skeleton",
          items: [],
        },
        {
          disabled: true,
          files: ["ui/slider.tsx"],
          title: "Slider",
          href: "/docs/components/slider",
          items: [],
        },
        {
          disabled: true,
          files: ["ui/sonner.tsx"],
          title: "Sonner",
          href: "/docs/components/sonner",
          items: [],
          label: "New",
        },
        {
          disabled: true,
          files: ["ui/switch.tsx"],
          title: "Switch",
          href: "/docs/components/switch",
          items: [],
        },
        {
          disabled: true,
          files: ["ui/table.tsx"],
          title: "Table",
          href: "/docs/components/table",
          items: [],
        },
        {
          disabled: true,
          files: ["ui/tabs.tsx"],
          title: "Tabs",
          href: "/docs/components/tabs",
          items: [],
        },
        {
          disabled: true,
          files: ["ui/textarea.tsx"],
          title: "Textarea",
          href: "/docs/components/textarea",
          items: [],
        },
        {
          disabled: true,
          files: ["ui/toast.tsx", "ui/use-toast.ts", "ui/toaster.tsx"],
          title: "Toast",
          href: "/docs/components/toast",
          items: [],
        },
        {
          disabled: true,
          files: ["ui/toggle.tsx"],
          title: "Toggle",
          href: "/docs/components/toggle",
          items: [],
        },
        {
          disabled: true,
          files: ["ui/toggle-group.tsx"],
          title: "Toggle Group",
          href: "/docs/components/toggle-group",
          items: [],
        },
        {
          disabled: true,
          files: ["ui/tooltip.tsx"],
          title: "Tooltip",
          href: "/docs/components/tooltip",
          items: [],
        },
      ],
    },
  ],
};
